import Link from "next/link";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import { useRouter } from "next/router";

export default function Home() {
  const router = useRouter();

  const blog = [
    {
      id: "1",
      value: "shatish_blog",
    },
    {
      id: "2",
      value: "bhautik_blog",
    },
  ];

  const handleRoute = () => {
    router.push({ pathname: "test/[id]/[IDid]", query: { id: "1", IDid: "2" } });
  };
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Navigate To Dynamic Routes </h1>
      <ul>
        <li>
          <Link href="/home">home</Link>
        </li>
        <li>
          <Link replace href="/home">
            home (You can not use Go back and Hold to history)
          </Link>
        </li>
        <li>
          <Link href="/home/Desais_home">home/Desai's Home</Link>
        </li>
      </ul>
      <h1>Navigate To Dynamic Routes -{">"} Blog Route </h1>
      <ul>
        <li>
          <Link href="/blog">blog</Link>
        </li>
        {blog.map((blog) => (
          <li key={blog.id}>
            <Link href={`blog/${blog.value}`}>{blog.value}</Link>
          </li>
        ))}
      </ul>
      <h1>
        Navigate To Dynamic Routes -{">"} Blog Route -{">"} Using Pathname and
        Query Properties
      </h1>
      <ul>
        <li>
          <Link href="/blog">blog</Link>
        </li>
        {blog.map((blog) => (
          <li key={blog.id}>
            <Link href={{ pathname: "/blog/[id]", query: { id: blog.value } }}>
              {blog.value}
            </Link>
          </li>
        ))}
      </ul>
      <h1>
        Navigating Programmatically [ using router.push and router.replace ]
      </h1>
      <li>
        <button onClick={handleRoute}>Hit Me!!</button>
      </li>
    </div>
  );
}
